# .readthedocs.yml
version: 2

# 构建环境
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Sphinx配置
sphinx:
  configuration: source/conf.py

# Python依赖
python:
  install:
    - requirements: source/requirements.txt

# 输出格式（可选）
formats:
  - htmlzip
  - pdf
