# .readthedocs.yml
version: 2

# 指定使用 main 分支
defaults:
  version: latest  # 使用最新版本
  branch: main     # 指定 main 分支

# 构建环境
build:
  os: ubuntu-22.04    # 使用Ubuntu 22.04
  tools:
    python: "3.11"     # Python版本，推荐3.8+

# Sphinx配置
sphinx:
  configuration: source/conf.py  # 注意路径：doc/source/conf.py

# Python依赖安装
python:
  install:
    # 安装文档依赖
    - requirements: source/requirements.txt
    
    # 可选：如果你有项目自身的依赖
    # - requirements: requirements.txt
    
    # 可选：如果你想安装当前项目
    # - method: pip
    #   path: .

# 输出格式（可选）
formats:
  - htmlzip    # 打包的HTML
  - pdf        # PDF文档
  # - epub     # EPUB电子书（可选）

# 环境变量（可选）
env:
  variables:
    READTHEDOCS: "true"
